# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# BufferAnalysis.py
# Created on: 2018-01-10 10:53:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# Buffer a selected accident and select properties within the buffer.

# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
env.overwriteOutput = True

import csv, os


# Local variables:
Parcels = "D:\\GISProjects\\Accident\\Accident.gdb\\Parcels"

AccidentTemplate = "D:\\GISProjects\\Accident\\Accident.gdb\\AccidentTemplate"
AccidentTemplate_Buffer1 = "D:\\GISProjects\\Accident\\Accident.gdb\\AccidentTemplate_Buffer1"
PD_Notify = "D:\\GISProjects\\Accident\\Accident.gdb\\PD_Notify"

# Process: Buffer
r = arcpy.Buffer_analysis(AccidentTemplate, AccidentTemplate_Buffer1, "500 Feet", "FULL", "ROUND", "NONE", "", "PLANAR")
print(r[0])

# Process: make feature layer - required for selection (layer in a map is required to be able to run outside arcGIS)
r = arcpy.MakeFeatureLayer_management(Parcels, "parcels2")
print(r[0])

# Process: Select Layer By Location
r = arcpy.SelectLayerByLocation_management("Parcels2", "INTERSECT", AccidentTemplate_Buffer1, "", "NEW_SELECTION", "NOT_INVERT")
print(r[0])

# Process: Copy Rows
r = arcpy.CopyRows_management("Parcels2", PD_Notify, "")
print(r[0])

# Process: Add Field
r = arcpy.AddField_management(PD_Notify, "address", "TEXT", "", "", "50", "", "NULLABLE", "NON_REQUIRED", "")
print(r[0])

# Process: Calculate Field
r = arcpy.CalculateField_management(PD_Notify, "address", "!House_Num! + ' ' + !Street_Name! + ' ' + !Street_Type!", "PYTHON_9.3", "")
print(r[0])

# Process: Delete Field
r = arcpy.DeleteField_management(PD_Notify, "SubName;BLK;LotNo;Pre_Type;Pre_Dir;House_Num;Street_Name;Street_Type;Suffix_Dir;Use_Code;PlatStatus")
print(r[0])

arcpy.CopyRows_management(r,"D:/GISProjects/accident/temp.txt")
filein= open("D:/GISProjects/accident/temp.txt", 'r')

for row in csv.reader(filein):
    outstr = row[-1]
    print(outstr)

filein.close()
os.remove("D:/GISProjects/accident/temp.txt")